name: Linting

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: '1.1.12'
      - name: Install deps
        run: poetry install
      - uses: pre-commit/action@v2.0.3
